= k8s_config

Ansible role for managing Kubernetes configuration

== Requirements

Ansible 2.9+

k8s module support

== Installation

Install with `ansible-galaxy`:

----
ansible-galaxy install git+https://github.com/redhat-gpte-devopsautomation/k8s_config.git,0.1.6
----

== Role Variables

Kubernetes configuration is specified through role variables.
These variables can be stored in the ansible inventory or dynamically loaded with `include_vars` and other methods provided by ansible.

=== Authentication Variables

The following variables are provided for cluster authentication.
If the host kubeconfig is already authenticated to the target cluster then no authentication variables are required.

These variables map to parameters of the `k8s` and `k8s_info` modules.

* `k8s_api_ca_cert` - Maps to `ca_cert`, which is the certificate provided to identify the client to the server when `client_cert` is also provided.

* `k8s_api_client_cert` - Maps to `client_cert`.

* `k8s_api_client_key` - Maps to `client_key`.

* `k8s_api_token` - Maps to `api_key`.

* `k8s_api_url` - Maps to `host`, which is the cluster API URL.

* `k8s_api_validate_certs` - Maps to `validate_certs`.

* `k8s_kubeconfig` - Maps to `kubeconfig`.

User and service account tokens are the preferred method of authentication for `k8s_config`,
The parameters `k8s_api_username` and `k8s_api_password` may be provided to authenticate to the cluster API to receive a token which will then be used in subsequent API communication.

=== Configuration Variables

==== Configuration Sources

Configuration sources can be configured with `k8s_config_sources`.
If provided, configuration sources will be used to load variables and be added to the search path for files and templates referended in `k8s_config` variables.

Settings for configuration sources:

* `name` -
  Source name, required.

* `base_path` -
  Base directory searched for configuration.
  If not provided then the root of the source git repository is used for git sources.
  Base path is optional for git config sources but required for local config sources.

* `config_search_path` -
  List of search paths relative to the base path used to find variables, files, and templates.
  The values in `config_search_path` are relative to `base_path`.
  If `config_search_path` is not given in `k8s_config_sources` then it can be provided by defining `k8s_config_search_path` in a `main.yaml` file located in the base path.
  If no search path is given or discovered, then the base path is added to the search path.

* `git` -
  Dictionary of parameters passed to the `git` module to clone the git repository.
  This should at least include `repo`.

* `when` -
  Optional condition for loading configuration source.
  This can be useful to conditionally load a configuration source depending on whether credentials are available.

==== Cluster configuration

* `k8s_resources` -
  List of Kubernetes resource definitions.
  Resource definitions may be given as dictionaries described below.
  Namespaced resources given in this variables should include `metadata.namespace`.

* `k8s_namespaces` -
  Dictionary of Kubernetes namespaces and configuration to apply to the namespace.
  If a namespace does not exist then it will be created dynamically.
  OpenShift ProjectRequests are used to create namespace if direct creation is not permitted.

** `resources` - List of Kubernetes resource definitions to apply to the namespace.

==== Resource Definitions:

Each resource definition is given as a dictionary.
The presence of the key `definition`, `file`, `openshift_template`, or `template` determines how resource definitions are handled.

* `definition` - Direct resource definition within the Ansible variable:
+
----
definition:
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: myconfig
  data:
    hostname: k8s.example.com
----

* `file` - File lookup of resources.
The value must be a file name which can be found in the Ansible file search path.
Multiple resource definitions can be included in a single file by including a resource of kind `v1/List` and by including multiple YAML documents in the file.
+
----
file: configmap.yaml
----

* `openshift_template` - OpenShift template file and parameters.
The file can be specified with `file` or `url`.
A dictionary, `parameters` is used for template parameters.
The `oc` command must be installed to process the template on the host.
+
----
openshift_template:
  file: openshift-template.yaml
  parameters:
    NAME: myconfig
    HOSTNAME: k8s.example.com
----

* `template` - Ansible Jinja2 template with file and variables.
The template file must be a file name which can be found in the Ansible template search path.
Variables provided are in addition to standard Ansible variables such as inventory host variables.
+
----
template:
  file: configmap.yaml.j2
  vars:
    name: myconfig
    hostname: k8s.example.com
----

* `when` - All resources support use of when conditions to control processing.
For example, a template may be conditionally processed depending on variables being set.

=== Multi-cluster Support

The variable `k8s_clusters` can be set to configure multiple kubernetes clusters with a single role execution.
`k8s_clusters` is given as a list of dictionaries.
Each cluster dictionary may specify:

* `api` - API connection and authentication settings, including:

** `ca_cert` - Cluster override for `k8s_api_ca_cert`

** `client_cert` - Cluster override for `k8s_api_client_cert`

** `client_key` - Cluster override for `k8s_api_client_key`

** `token` - Cluster override for `k8s_api_token`

** `url` - Cluster override for `k8s_api_url`

** `validate_certs` - Cluster override for `k8s_api_validate_certs`

* `namespaces` - Cluster override for `k8s_namespaces`

* `resources` - Cluster override for `k8s_resources`


== Example Playbook

----
- hosts: localhost
  gather_facts: false
  roles:
  - role: k8s_config
----

== License

GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

== Author Information

Johnathan Kupferer
