---
- name: >-
    {{ _k8s_cluster_name }} create temp dir for
    {{ _k8s_resources_item.name|default('Helm Template') }}
  tempfile:
    state: directory
  register: r_helm_tmp
  changed_when: false

- name: >-
    {{ _k8s_cluster_name }} git clone helm source
    {{ _k8s_resources_item.name|default('Helm Template') }}
  k8s_config_git_clone:
    dest: "{{ r_helm_tmp.path }}/source"
    module_args: "{{ _k8s_resources_item.helm_template.git }}"
  when: >-
    'git' in _k8s_resources_item.helm_template
  changed_when: false

- name: >-
    {{ _k8s_cluster_name }} write values file for
    {{ _k8s_resources_item.name|default('Helm Template') }}
  copy:
    content: "{{ _k8s_resources_item.helm_template.get('values', {}) | to_json }}"
    dest: "{{ r_helm_tmp.path }}/values.json"
  when: _k8s_resources_item.helm_template.get('values', {})
  changed_when: false

- name: >-
    {{ _k8s_cluster_name }} process
    {{ _k8s_resources_item.name|default('Helm Template') }}
  command: >-
    {{ helm_cmd }} template
    {% if 'release_name' in _k8s_resources_item.helm_template %}
    {{ _k8s_resources_item.helm_template.release_name }}
    {% endif %}
    {% if _k8s_resources_item.helm_template.include_crds | default(false) | bool %}
    --include-crds
    {% endif %}
    {% if 'namespace' in _k8s_resources_item.helm_template %}
    --namespace {{ _k8s_resources_item.helm_template.namespace | quote }}
    {% elif _k8s_namespace_name is defined %}
    --namespace {{ _k8s_namespace_name | quote }}
    {% endif %}
    {% if 'chart' in _k8s_resources_item.helm_template %}
    {{ _k8s_resources_item.helm_template.chart | quote }}
    {%   if 'repo' in _k8s_resources_item.helm_template %}
    --repo {{ _k8s_resources_item.helm_template.repo | quote }}
    {%   endif %}
    {%   if 'version' in _k8s_resources_item.helm_template %}
    --version {{ _k8s_resources_item.helm_template.version | quote }}
    {%   endif %}
    {% elif 'git' in _k8s_resources_item.helm_template %}
    {{ (r_helm_tmp.path ~ '/source/' ~ _k8s_resources_item.helm_template.dir | default('')) | quote }}
    {% else %}
    {{ lookup('first_found', {'paths': _helm_paths, 'files': _k8s_resources_item.helm_template.dir}) | quote }}
    {% endif %}
    {% if _k8s_resources_item.helm_template.get('values', {}) %}
    --values {{ (r_helm_tmp.path ~ '/values.json') | quote }}
    {% endif %}
  vars:
    _helm_paths: >-
      {{ k8s_config_search_path | map('regex_replace', '$', '/helm') | list }}
  changed_when: false
  check_mode: false
  register: _k8s_process_helm_template

- name: >-
    {{ _k8s_cluster_name }} remove temp dir for
    {{ _k8s_resources_item.name|default('Helm Template') }}
  file:
    state: absent
    path: "{{ r_helm_tmp.path }}"
  when: _k8s_resources_item.helm_template.get('values', {})
  changed_when: false

- name: >-
    {{ _k8s_cluster_name }} process
    {{ _k8s_resources_item.name }} resources
  include_tasks: k8s-definition.yaml
  vars:
    _k8s_resources_item:
      definition: "{{ _k8s_process_helm_template.stdout | from_yaml_all | list }}"
      name: >-
        {{ _k8s_namespace_resources_item.name
         | default(_k8s_cluster_resources_item.name)
         | default('resource')
        }}
