---
- name: Git clone config source {{ _k8s_config_source.name }}
  k8s_config_git_clone:
    dest: "{{ _k8s_config_source_cache_dir }}"
    module_args: "{{ _k8s_config_source.git }}"
  changed_when: false
  check_mode: false
  delegate_to: localhost
  when: >-
    'git' in _k8s_config_source

- name: Include main config for {{ _k8s_config_source.name }}
  include_vars:
    file: "{{ k8s_config_main_file }}"
    name: k8s_config_main
  vars:
    k8s_config_main_file: >-
      {{ lookup('first_found', {
        'files': ['main.yaml', 'main.yml', 'main.json'],
        'paths': [_k8s_config_source_base_path]
      }, errors='ignore') }}
  when: k8s_config_main_file != ''

- name: Update k8s_config_search_path
  set_fact:
    k8s_config_search_path: >-
      {{ _k8s_config_source.config_search_path
       | default(k8s_config_main.k8s_config_search_path)
       | default([''])
       | map('regex_replace', '^', _k8s_config_source_base_path ~ '/')
       | list
       + k8s_config_search_path | default([])
      }}
  run_once: True

- name: Include vars from included config search path for {{ _k8s_config_source.name }}
  include_vars:
    depth: 1
    dir: "{{ _k8s_config_source_dir }}"
    files_matching: "^[^.].*\\.(ya?ml|json)"
  loop: >-
    {{ _k8s_config_source.config_search_path
     | default(k8s_config_main.k8s_config_search_path)
     | default([''])
     | map('regex_replace', '^', _k8s_config_source_base_path ~ '/')
     | reverse
     | list }}
  loop_control:
    loop_var: _k8s_config_source_dir
  when: _k8s_config_source_dir is directory
